version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      # - .:/app
      - ./demo/webserver/database.db:/app/demo/webserver/database.db
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

volumes:
  db-data:
